GC_FUNCTIONS = True
USE_SERIAL = True
# BKLIGHT_ON = True
# USE_NAND = True
# USE_UBI = True

BOARD := rs90

VARIANTS := v10 v11
JZ_VERSION = 4750

CFLAGS_all := -mips32
CFLAGS_v10 := -DCFG_SDRAM_ROW=12 -DCFG_SDRAM_COL=10
CFLAGS_v11 := -DCFG_SDRAM_ROW=13 -DCFG_SDRAM_COL=9
