GC_FUNCTIONS = True
USE_SERIAL = True
# BKLIGHT_ON = True
USE_NAND = True
USE_UBI = True

BOARD := a320

VARIANTS := a320
JZ_VERSION = 4740

CFLAGS_all := -mips32 -DSDRAM_WB9812G6IH_6 -DSDRAM_BUS_WIDTH=32
